name: deploy
on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy to VPS
        runs-on: ubuntu-22.04
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: 80.240.126.22
                  port: 2222
                  username: cofeproyect
                  key: ${{secrets.PRIVATE_KEY}}
                  script: "cd /var/www/html/proyectoCafe; git pull origin master; composer install; npm install; php artisan optimize; php artisan view:cache; npm run build"